name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install dependencies
      run: |
        cd eshanee-chetan-backend
        npm ci
        
    - name: Run tests (optional)
      run: |
        cd eshanee-chetan-backend
        # npm test
        
    - name: Build application
      run: |
        cd eshanee-chetan-backend
        # Add build step if you have one
        # npm run build
        
    - name: Create deployment package
      run: |
        cd eshanee-chetan-backend
        # Remove dev dependencies and files not needed in production
        npm prune --production
        # Create a clean package for deployment
        mkdir -p ../deployment-package
        cp -r . ../deployment-package/
        # Remove unnecessary files
        rm -rf ../deployment-package/node_modules/.cache || true
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'eshanee-chetan-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './deployment-package'
